<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VerificationSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $this->seedNames('account_type', [
            'Business',
            'Institutional investor',
            'Fund',
            'Family office',
            'Angel investor',
            'Syndicate',
            'Government or development institution',
            'Other',
        ], $now);

        $this->seedNames('applicant_profile', [
            'Company',
            'Partnership',
            'Sole proprietor',
            'Nonprofit',
            'Trust',
            'Cooperative',
            'Public body',
            'Individual investor',
        ], $now);

        $this->seedNames('legal_structure', [
            'Private limited',
            'Public limited',
            'Partnership',
            'Sole proprietorship',
            'Nonprofit',
            'Trust',
            'Fund',
            'Other',
        ], $now);

        $this->seedNames('ownership_type', [
            'Private',
            'Public',
            'State-owned',
        ], $now);

        $this->seedNames('investor_status', [
            'Not an Investor',
            'Retail',
            'Accredited or Qualified',
            'Professional',
            'Institutional',
        ], $now);

        $this->seedNames('investment_role', [
            'Investor',
            'Fund manager',
            'Advisor',
            'Limited partner',
            'Lead investor',
            'Co-investor',
            'Other',
        ], $now);

        DB::table('prefered_investment_stages')->upsert([
            $this->stage('Seed', 'SEED', $now),
            $this->stage('Series A', 'SERIES_A', $now),
            $this->stage('Series B', 'SERIES_B', $now),
            $this->stage('Series C', 'SERIES_C', $now),
            $this->stage('Growth', 'GROWTH', $now),
        ], ['code'], ['name', 'description', 'updated_at', 'who']);

        /*
         * Populate this array from the attached currency list:
         * Country name, currency name, ISO currency code, numeric ISO code.
         */
        $currencies = [
            ['country_name' => 'AFGHANISTAN', 'name' => 'Afghani', 'code' => 'AFN', 'description' => 'ISO numeric code: 971'],
            ['country_name' => 'ALBANIA', 'name' => 'Lek', 'code' => 'ALL', 'description' => 'ISO numeric code: 008'],
            ['country_name' => 'ALGERIA', 'name' => 'Algerian Dinar', 'code' => 'DZD', 'description' => 'ISO numeric code: 012'],
            ['country_name' => 'AMERICAN SAMOA', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'ANDORRA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'ANGOLA', 'name' => 'Kwanza', 'code' => 'AOA', 'description' => 'ISO numeric code: 973'],
            ['country_name' => 'ANGUILLA', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'ANTARCTICA', 'name' => 'No universal currency', 'code' => null, 'description' => null],
            ['country_name' => 'ANTIGUA AND BARBUDA', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'ARGENTINA', 'name' => 'Argentine Peso', 'code' => 'ARS', 'description' => 'ISO numeric code: 032'],
            ['country_name' => 'ARMENIA', 'name' => 'Armenian Dram', 'code' => 'AMD', 'description' => 'ISO numeric code: 051'],
            ['country_name' => 'ARUBA', 'name' => 'Aruban Florin', 'code' => 'AWG', 'description' => 'ISO numeric code: 533'],
            ['country_name' => 'AUSTRALIA', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'AUSTRIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'AZERBAIJAN', 'name' => 'Azerbaijan Manat', 'code' => 'AZN', 'description' => 'ISO numeric code: 944'],
            ['country_name' => 'BAHAMAS (THE)', 'name' => 'Bahamian Dollar', 'code' => 'BSD', 'description' => 'ISO numeric code: 044'],
            ['country_name' => 'BAHRAIN', 'name' => 'Bahraini Dinar', 'code' => 'BHD', 'description' => 'ISO numeric code: 048'],
            ['country_name' => 'BANGLADESH', 'name' => 'Taka', 'code' => 'BDT', 'description' => 'ISO numeric code: 050'],
            ['country_name' => 'BARBADOS', 'name' => 'Barbados Dollar', 'code' => 'BBD', 'description' => 'ISO numeric code: 052'],
            ['country_name' => 'BELARUS', 'name' => 'Belarusian Ruble', 'code' => 'BYN', 'description' => 'ISO numeric code: 933'],
            ['country_name' => 'BELGIUM', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'BELIZE', 'name' => 'Belize Dollar', 'code' => 'BZD', 'description' => 'ISO numeric code: 084'],
            ['country_name' => 'BENIN', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'BERMUDA', 'name' => 'Bermudian Dollar', 'code' => 'BMD', 'description' => 'ISO numeric code: 060'],
            ['country_name' => 'BHUTAN', 'name' => 'Ngultrum', 'code' => 'BTN', 'description' => 'ISO numeric code: 064'],
            ['country_name' => 'BHUTAN', 'name' => 'Indian Rupee', 'code' => 'INR', 'description' => 'ISO numeric code: 356'],
            ['country_name' => 'BOLIVIA (PLURINATIONAL STATE OF)', 'name' => 'Boliviano', 'code' => 'BOB', 'description' => 'ISO numeric code: 068'],
            ['country_name' => 'BOLIVIA (PLURINATIONAL STATE OF)', 'name' => 'Mvdol', 'code' => 'BOV', 'description' => 'ISO numeric code: 984'],
            ['country_name' => 'BONAIRE, SINT EUSTATIUS AND SABA', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'BOSNIA AND HERZEGOVINA', 'name' => 'Convertible Mark', 'code' => 'BAM', 'description' => 'ISO numeric code: 977'],
            ['country_name' => 'BOTSWANA', 'name' => 'Pula', 'code' => 'BWP', 'description' => 'ISO numeric code: 072'],
            ['country_name' => 'BOUVET ISLAND', 'name' => 'Norwegian Krone', 'code' => 'NOK', 'description' => 'ISO numeric code: 578'],
            ['country_name' => 'BRAZIL', 'name' => 'Brazilian Real', 'code' => 'BRL', 'description' => 'ISO numeric code: 986'],
            ['country_name' => 'BRITISH INDIAN OCEAN TERRITORY (THE)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'BRUNEI DARUSSALAM', 'name' => 'Brunei Dollar', 'code' => 'BND', 'description' => 'ISO numeric code: 096'],
            ['country_name' => 'BULGARIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'BURKINA FASO', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'BURUNDI', 'name' => 'Burundi Franc', 'code' => 'BIF', 'description' => 'ISO numeric code: 108'],
            ['country_name' => 'CABO VERDE', 'name' => 'Cabo Verde Escudo', 'code' => 'CVE', 'description' => 'ISO numeric code: 132'],
            ['country_name' => 'CAMBODIA', 'name' => 'Riel', 'code' => 'KHR', 'description' => 'ISO numeric code: 116'],
            ['country_name' => 'CAMEROON', 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'description' => 'ISO numeric code: 950'],
            ['country_name' => 'CANADA', 'name' => 'Canadian Dollar', 'code' => 'CAD', 'description' => 'ISO numeric code: 124'],
            ['country_name' => 'CAYMAN ISLANDS (THE)', 'name' => 'Cayman Islands Dollar', 'code' => 'KYD', 'description' => 'ISO numeric code: 136'],
            ['country_name' => 'CENTRAL AFRICAN REPUBLIC (THE)', 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'description' => 'ISO numeric code: 950'],
            ['country_name' => 'CHAD', 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'description' => 'ISO numeric code: 950'],
            ['country_name' => 'CHILE', 'name' => 'Unidad de Fomento', 'code' => 'CLF', 'description' => 'ISO numeric code: 990'],
            ['country_name' => 'CHILE', 'name' => 'Chilean Peso', 'code' => 'CLP', 'description' => 'ISO numeric code: 152'],
            ['country_name' => 'CHINA', 'name' => 'Yuan Renminbi', 'code' => 'CNY', 'description' => 'ISO numeric code: 156'],
            ['country_name' => 'CHRISTMAS ISLAND', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'COCOS (KEELING) ISLANDS (THE)', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'COLOMBIA', 'name' => 'Colombian Peso', 'code' => 'COP', 'description' => 'ISO numeric code: 170'],
            ['country_name' => 'COLOMBIA', 'name' => 'Unidad de Valor Real', 'code' => 'COU', 'description' => 'ISO numeric code: 970'],
            ['country_name' => 'COMOROS (THE)', 'name' => 'Comorian Franc', 'code' => 'KMF', 'description' => 'ISO numeric code: 174'],
            ['country_name' => 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)', 'name' => 'Congolese Franc', 'code' => 'CDF', 'description' => 'ISO numeric code: 976'],
            ['country_name' => 'CONGO (THE)', 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'description' => 'ISO numeric code: 950'],
            ['country_name' => 'COOK ISLANDS (THE)', 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'description' => 'ISO numeric code: 554'],
            ['country_name' => 'COSTA RICA', 'name' => 'Costa Rican Colon', 'code' => 'CRC', 'description' => 'ISO numeric code: 188'],
            ['country_name' => 'CROATIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'CUBA', 'name' => 'Cuban Peso', 'code' => 'CUP', 'description' => 'ISO numeric code: 192'],
            ['country_name' => 'CUBA', 'name' => 'Cuban Peso', 'code' => 'CUP', 'description' => 'ISO numeric code: 192'],
            ['country_name' => 'CURAÇAO', 'name' => 'Caribbean Guilder', 'code' => 'XCG', 'description' => 'ISO numeric code: 532'],
            ['country_name' => 'CYPRUS', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'CZECH REPUBLIC (THE)', 'name' => 'Czech Koruna', 'code' => 'CZK', 'description' => 'ISO numeric code: 203'],
            ['country_name' => 'CÔTE D\'IVOIRE', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'DENMARK', 'name' => 'Danish Krone', 'code' => 'DKK', 'description' => 'ISO numeric code: 208'],
            ['country_name' => 'DJIBOUTI', 'name' => 'Djibouti Franc', 'code' => 'DJF', 'description' => 'ISO numeric code: 262'],
            ['country_name' => 'DOMINICA', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'DOMINICAN REPUBLIC (THE)', 'name' => 'Dominican Peso', 'code' => 'DOP', 'description' => 'ISO numeric code: 214'],
            ['country_name' => 'ECUADOR', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'EGYPT', 'name' => 'Egyptian Pound', 'code' => 'EGP', 'description' => 'ISO numeric code: 818'],
            ['country_name' => 'EL SALVADOR', 'name' => 'El Salvador Colon', 'code' => 'SVC', 'description' => 'ISO numeric code: 222'],
            ['country_name' => 'EL SALVADOR', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'EQUATORIAL GUINEA', 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'description' => 'ISO numeric code: 950'],
            ['country_name' => 'ERITREA', 'name' => 'Nakfa', 'code' => 'ERN', 'description' => 'ISO numeric code: 232'],
            ['country_name' => 'ESTONIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'ESWATINI', 'name' => 'Lilangeni', 'code' => 'SZL', 'description' => 'ISO numeric code: 748'],
            ['country_name' => 'ETHIOPIA', 'name' => 'Ethiopian Birr', 'code' => 'ETB', 'description' => 'ISO numeric code: 230'],
            ['country_name' => 'FALKLAND ISLANDS (THE) [MALVINAS]', 'name' => 'Falkland Islands Pound', 'code' => 'FKP', 'description' => 'ISO numeric code: 238'],
            ['country_name' => 'FAROE ISLANDS (THE)', 'name' => 'Danish Krone', 'code' => 'DKK', 'description' => 'ISO numeric code: 208'],
            ['country_name' => 'FIJI', 'name' => 'Fiji Dollar', 'code' => 'FJD', 'description' => 'ISO numeric code: 242'],
            ['country_name' => 'FINLAND', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'FRANCE', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'FRENCH GUIANA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'FRENCH POLYNESIA', 'name' => 'CFP Franc', 'code' => 'XPF', 'description' => 'ISO numeric code: 953'],
            ['country_name' => 'FRENCH SOUTHERN TERRITORIES (THE)', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'GABON', 'name' => 'CFA Franc BEAC', 'code' => 'XAF', 'description' => 'ISO numeric code: 950'],
            ['country_name' => 'GAMBIA (THE)', 'name' => 'Dalasi', 'code' => 'GMD', 'description' => 'ISO numeric code: 270'],
            ['country_name' => 'GEORGIA', 'name' => 'Lari', 'code' => 'GEL', 'description' => 'ISO numeric code: 981'],
            ['country_name' => 'GERMANY', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'GHANA', 'name' => 'Ghana Cedi', 'code' => 'GHS', 'description' => 'ISO numeric code: 936'],
            ['country_name' => 'GIBRALTAR', 'name' => 'Gibraltar Pound', 'code' => 'GIP', 'description' => 'ISO numeric code: 292'],
            ['country_name' => 'GREECE', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'GREENLAND', 'name' => 'Danish Krone', 'code' => 'DKK', 'description' => 'ISO numeric code: 208'],
            ['country_name' => 'GRENADA', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'GUADELOUPE', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'GUAM', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'GUATEMALA', 'name' => 'Quetzal', 'code' => 'GTQ', 'description' => 'ISO numeric code: 320'],
            ['country_name' => 'GUERNSEY', 'name' => 'Pound Sterling', 'code' => 'GBP', 'description' => 'ISO numeric code: 826'],
            ['country_name' => 'GUINEA', 'name' => 'Guinean Franc', 'code' => 'GNF', 'description' => 'ISO numeric code: 324'],
            ['country_name' => 'GUINEA-BISSAU', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'GUYANA', 'name' => 'Guyana Dollar', 'code' => 'GYD', 'description' => 'ISO numeric code: 328'],
            ['country_name' => 'HAITI', 'name' => 'Gourde', 'code' => 'HTG', 'description' => 'ISO numeric code: 332'],
            ['country_name' => 'HAITI', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'HEARD ISLAND AND McDONALD ISLANDS', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'HOLY SEE (THE)', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'HONDURAS', 'name' => 'Lempira', 'code' => 'HNL', 'description' => 'ISO numeric code: 340'],
            ['country_name' => 'HONG KONG', 'name' => 'Hong Kong Dollar', 'code' => 'HKD', 'description' => 'ISO numeric code: 344'],
            ['country_name' => 'HUNGARY', 'name' => 'Forint', 'code' => 'HUF', 'description' => 'ISO numeric code: 348'],
            ['country_name' => 'ICELAND', 'name' => 'Iceland Krona', 'code' => 'ISK', 'description' => 'ISO numeric code: 352'],
            ['country_name' => 'INDIA', 'name' => 'Indian Rupee', 'code' => 'INR', 'description' => 'ISO numeric code: 356'],
            ['country_name' => 'INDONESIA', 'name' => 'Rupiah', 'code' => 'IDR', 'description' => 'ISO numeric code: 360'],
            ['country_name' => 'INTERNATIONAL MONETARY FUND (IMF)', 'name' => 'SDR (Special Drawing Right)', 'code' => 'XDR', 'description' => 'ISO numeric code: 960'],
            ['country_name' => 'IRAN (ISLAMIC REPUBLIC OF)', 'name' => 'Iranian Rial', 'code' => 'IRR', 'description' => 'ISO numeric code: 364'],
            ['country_name' => 'IRAQ', 'name' => 'Iraqi Dinar', 'code' => 'IQD', 'description' => 'ISO numeric code: 368'],
            ['country_name' => 'IRELAND', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'ISLE OF MAN', 'name' => 'Pound Sterling', 'code' => 'GBP', 'description' => 'ISO numeric code: 826'],
            ['country_name' => 'ISRAEL', 'name' => 'New Israeli Sheqel', 'code' => 'ILS', 'description' => 'ISO numeric code: 376'],
            ['country_name' => 'ITALY', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'JAMAICA', 'name' => 'Jamaican Dollar', 'code' => 'JMD', 'description' => 'ISO numeric code: 388'],
            ['country_name' => 'JAPAN', 'name' => 'Yen', 'code' => 'JPY', 'description' => 'ISO numeric code: 392'],
            ['country_name' => 'JERSEY', 'name' => 'Pound Sterling', 'code' => 'GBP', 'description' => 'ISO numeric code: 826'],
            ['country_name' => 'JORDAN', 'name' => 'Jordanian Dinar', 'code' => 'JOD', 'description' => 'ISO numeric code: 400'],
            ['country_name' => 'KAZAKHSTAN', 'name' => 'Tenge', 'code' => 'KZT', 'description' => 'ISO numeric code: 398'],
            ['country_name' => 'KENYA', 'name' => 'Kenyan Shilling', 'code' => 'KES', 'description' => 'ISO numeric code: 404'],
            ['country_name' => 'KIRIBATI', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)', 'name' => 'North Korean Won', 'code' => 'KPW', 'description' => 'ISO numeric code: 408'],
            ['country_name' => 'KOREA (THE REPUBLIC OF)', 'name' => 'Won', 'code' => 'KRW', 'description' => 'ISO numeric code: 410'],
            ['country_name' => 'KUWAIT', 'name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'description' => 'ISO numeric code: 414'],
            ['country_name' => 'KYRGYZSTAN', 'name' => 'Som', 'code' => 'KGS', 'description' => 'ISO numeric code: 417'],
            ['country_name' => 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)', 'name' => 'Lao Kip', 'code' => 'LAK', 'description' => 'ISO numeric code: 418'],
            ['country_name' => 'LATVIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'LEBANON', 'name' => 'Lebanese Pound', 'code' => 'LBP', 'description' => 'ISO numeric code: 422'],
            ['country_name' => 'LESOTHO', 'name' => 'Loti', 'code' => 'LSL', 'description' => 'ISO numeric code: 426'],
            ['country_name' => 'LESOTHO', 'name' => 'Rand', 'code' => 'ZAR', 'description' => 'ISO numeric code: 710'],
            ['country_name' => 'LIBERIA', 'name' => 'Liberian Dollar', 'code' => 'LRD', 'description' => 'ISO numeric code: 430'],
            ['country_name' => 'LIBYA', 'name' => 'Libyan Dinar', 'code' => 'LYD', 'description' => 'ISO numeric code: 434'],
            ['country_name' => 'LIECHTENSTEIN', 'name' => 'Swiss Franc', 'code' => 'CHF', 'description' => 'ISO numeric code: 756'],
            ['country_name' => 'LITHUANIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'LUXEMBOURG', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'MACAO', 'name' => 'Pataca', 'code' => 'MOP', 'description' => 'ISO numeric code: 446'],
            ['country_name' => 'MADAGASCAR', 'name' => 'Malagasy Ariary', 'code' => 'MGA', 'description' => 'ISO numeric code: 969'],
            ['country_name' => 'MALAWI', 'name' => 'Malawi Kwacha', 'code' => 'MWK', 'description' => 'ISO numeric code: 454'],
            ['country_name' => 'MALAYSIA', 'name' => 'Malaysian Ringgit', 'code' => 'MYR', 'description' => 'ISO numeric code: 458'],
            ['country_name' => 'MALDIVES', 'name' => 'Rufiyaa', 'code' => 'MVR', 'description' => 'ISO numeric code: 462'],
            ['country_name' => 'MALI', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'MALTA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'MARSHALL ISLANDS (THE)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'MARTINIQUE', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'MAURITANIA', 'name' => 'Ouguiya', 'code' => 'MRU', 'description' => 'ISO numeric code: 929'],
            ['country_name' => 'MAURITIUS', 'name' => 'Mauritius Rupee', 'code' => 'MUR', 'description' => 'ISO numeric code: 480'],
            ['country_name' => 'MAYOTTE', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP', 'name' => 'ADB Unit of Account', 'code' => 'XUA', 'description' => 'ISO numeric code: 965'],
            ['country_name' => 'MEXICO', 'name' => 'Mexican Peso', 'code' => 'MXN', 'description' => 'ISO numeric code: 484'],
            ['country_name' => 'MEXICO', 'name' => 'Mexican Unidad de Inversion (UDI)', 'code' => 'MXV', 'description' => 'ISO numeric code: 979'],
            ['country_name' => 'MICRONESIA (FEDERATED STATES OF)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'MOLDOVA (THE REPUBLIC OF)', 'name' => 'Moldovan Leu', 'code' => 'MDL', 'description' => 'ISO numeric code: 498'],
            ['country_name' => 'MONACO', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'MONGOLIA', 'name' => 'Tugrik', 'code' => 'MNT', 'description' => 'ISO numeric code: 496'],
            ['country_name' => 'MONTENEGRO', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'MONTSERRAT', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'MOROCCO', 'name' => 'Moroccan Dirham', 'code' => 'MAD', 'description' => 'ISO numeric code: 504'],
            ['country_name' => 'MOZAMBIQUE', 'name' => 'Mozambique Metical', 'code' => 'MZN', 'description' => 'ISO numeric code: 943'],
            ['country_name' => 'MYANMAR', 'name' => 'Kyat', 'code' => 'MMK', 'description' => 'ISO numeric code: 104'],
            ['country_name' => 'NAMIBIA', 'name' => 'Namibia Dollar', 'code' => 'NAD', 'description' => 'ISO numeric code: 516'],
            ['country_name' => 'NAMIBIA', 'name' => 'Rand', 'code' => 'ZAR', 'description' => 'ISO numeric code: 710'],
            ['country_name' => 'NAURU', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'NEPAL', 'name' => 'Nepalese Rupee', 'code' => 'NPR', 'description' => 'ISO numeric code: 524'],
            ['country_name' => 'NETHERLANDS (THE)', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'NEW CALEDONIA', 'name' => 'CFP Franc', 'code' => 'XPF', 'description' => 'ISO numeric code: 953'],
            ['country_name' => 'NEW ZEALAND', 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'description' => 'ISO numeric code: 554'],
            ['country_name' => 'NICARAGUA', 'name' => 'Cordoba Oro', 'code' => 'NIO', 'description' => 'ISO numeric code: 558'],
            ['country_name' => 'NIGER (THE)', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'NIGERIA', 'name' => 'Naira', 'code' => 'NGN', 'description' => 'ISO numeric code: 566'],
            ['country_name' => 'NIUE', 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'description' => 'ISO numeric code: 554'],
            ['country_name' => 'NORFOLK ISLAND', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'NORTH MACEDONIA', 'name' => 'Denar', 'code' => 'MKD', 'description' => 'ISO numeric code: 807'],
            ['country_name' => 'NORTHERN MARIANA ISLANDS (THE)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'NORWAY', 'name' => 'Norwegian Krone', 'code' => 'NOK', 'description' => 'ISO numeric code: 578'],
            ['country_name' => 'OMAN', 'name' => 'Rial Omani', 'code' => 'OMR', 'description' => 'ISO numeric code: 512'],
            ['country_name' => 'PAKISTAN', 'name' => 'Pakistan Rupee', 'code' => 'PKR', 'description' => 'ISO numeric code: 586'],
            ['country_name' => 'PALAU', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'PALESTINE, STATE OF', 'name' => 'No universal currency', 'code' => null, 'description' => null],
            ['country_name' => 'PANAMA', 'name' => 'Balboa', 'code' => 'PAB', 'description' => 'ISO numeric code: 590'],
            ['country_name' => 'PANAMA', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'PAPUA NEW GUINEA', 'name' => 'Kina', 'code' => 'PGK', 'description' => 'ISO numeric code: 598'],
            ['country_name' => 'PARAGUAY', 'name' => 'Guarani', 'code' => 'PYG', 'description' => 'ISO numeric code: 600'],
            ['country_name' => 'PERU', 'name' => 'Sol', 'code' => 'PEN', 'description' => 'ISO numeric code: 604'],
            ['country_name' => 'PHILIPPINES (THE)', 'name' => 'Philippine Peso', 'code' => 'PHP', 'description' => 'ISO numeric code: 608'],
            ['country_name' => 'PITCAIRN', 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'description' => 'ISO numeric code: 554'],
            ['country_name' => 'POLAND', 'name' => 'Zloty', 'code' => 'PLN', 'description' => 'ISO numeric code: 985'],
            ['country_name' => 'PORTUGAL', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'PUERTO RICO', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'QATAR', 'name' => 'Qatari Rial', 'code' => 'QAR', 'description' => 'ISO numeric code: 634'],
            ['country_name' => 'ROMANIA', 'name' => 'Romanian Leu', 'code' => 'RON', 'description' => 'ISO numeric code: 946'],
            ['country_name' => 'RUSSIAN FEDERATION (THE)', 'name' => 'Russian Ruble', 'code' => 'RUB', 'description' => 'ISO numeric code: 643'],
            ['country_name' => 'RWANDA', 'name' => 'Rwanda Franc', 'code' => 'RWF', 'description' => 'ISO numeric code: 646'],
            ['country_name' => 'RÉUNION', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SAINT BARTHÉLEMY', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'name' => 'Saint Helena Pound', 'code' => 'SHP', 'description' => 'ISO numeric code: 654'],
            ['country_name' => 'SAINT KITTS AND NEVIS', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'SAINT LUCIA', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'SAINT MARTIN (FRENCH PART)', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SAINT PIERRE AND MIQUELON', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SAINT VINCENT AND THE GRENADINES', 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'description' => 'ISO numeric code: 951'],
            ['country_name' => 'SAMOA', 'name' => 'Tala', 'code' => 'WST', 'description' => 'ISO numeric code: 882'],
            ['country_name' => 'SAN MARINO', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SAO TOME AND PRINCIPE', 'name' => 'Dobra', 'code' => 'STN', 'description' => 'ISO numeric code: 930'],
            ['country_name' => 'SAUDI ARABIA', 'name' => 'Saudi Riyal', 'code' => 'SAR', 'description' => 'ISO numeric code: 682'],
            ['country_name' => 'SENEGAL', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'SERBIA', 'name' => 'Serbian Dinar', 'code' => 'RSD', 'description' => 'ISO numeric code: 941'],
            ['country_name' => 'SEYCHELLES', 'name' => 'Seychelles Rupee', 'code' => 'SCR', 'description' => 'ISO numeric code: 690'],
            ['country_name' => 'SIERRA LEONE', 'name' => 'Leone', 'code' => 'SLE', 'description' => 'ISO numeric code: 925'],
            ['country_name' => 'SINGAPORE', 'name' => 'Singapore Dollar', 'code' => 'SGD', 'description' => 'ISO numeric code: 702'],
            ['country_name' => 'SINT MAARTEN (DUTCH PART)', 'name' => 'Caribbean guilder', 'code' => 'XCG', 'description' => 'ISO numeric code: 532'],
            ['country_name' => 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"', 'name' => 'Sucre', 'code' => 'XSU', 'description' => 'ISO numeric code: 994'],
            ['country_name' => 'SLOVAKIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SLOVENIA', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SOLOMON ISLANDS', 'name' => 'Solomon Islands Dollar', 'code' => 'SBD', 'description' => 'ISO numeric code: 090'],
            ['country_name' => 'SOMALIA', 'name' => 'Somali Shilling', 'code' => 'SOS', 'description' => 'ISO numeric code: 706'],
            ['country_name' => 'SOUTH AFRICA', 'name' => 'Rand', 'code' => 'ZAR', 'description' => 'ISO numeric code: 710'],
            ['country_name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'name' => 'No universal currency', 'code' => null, 'description' => null],
            ['country_name' => 'SOUTH SUDAN', 'name' => 'South Sudanese Pound', 'code' => 'SSP', 'description' => 'ISO numeric code: 728'],
            ['country_name' => 'SPAIN', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
            ['country_name' => 'SRI LANKA', 'name' => 'Sri Lanka Rupee', 'code' => 'LKR', 'description' => 'ISO numeric code: 144'],
            ['country_name' => 'SUDAN (THE)', 'name' => 'Sudanese Pound', 'code' => 'SDG', 'description' => 'ISO numeric code: 938'],
            ['country_name' => 'SURINAME', 'name' => 'Surinam Dollar', 'code' => 'SRD', 'description' => 'ISO numeric code: 968'],
            ['country_name' => 'SVALBARD AND JAN MAYEN', 'name' => 'Norwegian Krone', 'code' => 'NOK', 'description' => 'ISO numeric code: 578'],
            ['country_name' => 'SWEDEN', 'name' => 'Swedish Krona', 'code' => 'SEK', 'description' => 'ISO numeric code: 752'],
            ['country_name' => 'SWITZERLAND', 'name' => 'WIR Euro', 'code' => 'CHE', 'description' => 'ISO numeric code: 947'],
            ['country_name' => 'SWITZERLAND', 'name' => 'Swiss Franc', 'code' => 'CHF', 'description' => 'ISO numeric code: 756'],
            ['country_name' => 'SWITZERLAND', 'name' => 'WIR Franc', 'code' => 'CHW', 'description' => 'ISO numeric code: 948'],
            ['country_name' => 'SYRIAN ARAB REPUBLIC', 'name' => 'Syrian Pound', 'code' => 'SYP', 'description' => 'ISO numeric code: 760'],
            ['country_name' => 'TAIWAN (PROVINCE OF CHINA)', 'name' => 'New Taiwan Dollar', 'code' => 'TWD', 'description' => 'ISO numeric code: 901'],
            ['country_name' => 'TAJIKISTAN', 'name' => 'Somoni', 'code' => 'TJS', 'description' => 'ISO numeric code: 972'],
            ['country_name' => 'TANZANIA, UNITED REPUBLIC OF', 'name' => 'Tanzanian Shilling', 'code' => 'TZS', 'description' => 'ISO numeric code: 834'],
            ['country_name' => 'THAILAND', 'name' => 'Baht', 'code' => 'THB', 'description' => 'ISO numeric code: 764'],
            ['country_name' => 'TIMOR-LESTE', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'TOGO', 'name' => 'CFA Franc BCEAO', 'code' => 'XOF', 'description' => 'ISO numeric code: 952'],
            ['country_name' => 'TOKELAU', 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'description' => 'ISO numeric code: 554'],
            ['country_name' => 'TONGA', 'name' => 'Pa’anga', 'code' => 'TOP', 'description' => 'ISO numeric code: 776'],
            ['country_name' => 'TRINIDAD AND TOBAGO', 'name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'description' => 'ISO numeric code: 780'],
            ['country_name' => 'TUNISIA', 'name' => 'Tunisian Dinar', 'code' => 'TND', 'description' => 'ISO numeric code: 788'],
            ['country_name' => 'TURKEY', 'name' => 'Turkish Lira', 'code' => 'TRY', 'description' => 'ISO numeric code: 949'],
            ['country_name' => 'TURKMENISTAN', 'name' => 'Turkmenistan New Manat', 'code' => 'TMT', 'description' => 'ISO numeric code: 934'],
            ['country_name' => 'TURKS AND CAICOS ISLANDS (THE)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'TUVALU', 'name' => 'Australian Dollar', 'code' => 'AUD', 'description' => 'ISO numeric code: 036'],
            ['country_name' => 'UGANDA', 'name' => 'Uganda Shilling', 'code' => 'UGX', 'description' => 'ISO numeric code: 800'],
            ['country_name' => 'UKRAINE', 'name' => 'Hryvnia', 'code' => 'UAH', 'description' => 'ISO numeric code: 980'],
            ['country_name' => 'UNITED ARAB EMIRATES (THE)', 'name' => 'UAE Dirham', 'code' => 'AED', 'description' => 'ISO numeric code: 784'],
            ['country_name' => 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)', 'name' => 'Pound Sterling', 'code' => 'GBP', 'description' => 'ISO numeric code: 826'],
            ['country_name' => 'UNITED STATES MINOR OUTLYING ISLANDS (THE)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'UNITED STATES OF AMERICA (THE)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'UNITED STATES OF AMERICA (THE)', 'name' => 'US Dollar (Next day)', 'code' => 'USN', 'description' => 'ISO numeric code: 997'],
            ['country_name' => 'URUGUAY', 'name' => 'Uruguay Peso en Unidades Indexadas (UI)', 'code' => 'UYI', 'description' => 'ISO numeric code: 940'],
            ['country_name' => 'URUGUAY', 'name' => 'Unidad Previsional', 'code' => 'UYW', 'description' => 'ISO numeric code: 927'],
            ['country_name' => 'URUGUAY', 'name' => 'Peso Uruguayo', 'code' => 'UYU', 'description' => 'ISO numeric code: 858'],
            ['country_name' => 'UZBEKISTAN', 'name' => 'Uzbekistan Sum', 'code' => 'UZS', 'description' => 'ISO numeric code: 860'],
            ['country_name' => 'VANUATU', 'name' => 'Vatu', 'code' => 'VUV', 'description' => 'ISO numeric code: 548'],
            ['country_name' => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)', 'name' => 'Bolívar Soberano', 'code' => 'VES', 'description' => 'ISO numeric code: 928'],
            ['country_name' => 'VENEZUELA (BOLIVARIAN REPUBLIC OF)', 'name' => 'Bolívar Soberano', 'code' => 'VED', 'description' => 'ISO numeric code: 926'],
            ['country_name' => 'VIET NAM', 'name' => 'Dong', 'code' => 'VND', 'description' => 'ISO numeric code: 704'],
            ['country_name' => 'VIRGIN ISLANDS (BRITISH)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'VIRGIN ISLANDS (U.S.)', 'name' => 'US Dollar', 'code' => 'USD', 'description' => 'ISO numeric code: 840'],
            ['country_name' => 'WALLIS AND FUTUNA', 'name' => 'CFP Franc', 'code' => 'XPF', 'description' => 'ISO numeric code: 953'],
            ['country_name' => 'WESTERN SAHARA', 'name' => 'Moroccan Dirham', 'code' => 'MAD', 'description' => 'ISO numeric code: 504'],
            ['country_name' => 'YEMEN', 'name' => 'Yemeni Rial', 'code' => 'YER', 'description' => 'ISO numeric code: 886'],
            ['country_name' => 'ZAMBIA', 'name' => 'Zambian Kwacha', 'code' => 'ZMW', 'description' => 'ISO numeric code: 967'],
            ['country_name' => 'ZIMBABWE', 'name' => 'Zimbabwe Gold', 'code' => 'ZWG', 'description' => 'ISO numeric code: 924'],
            ['country_name' => 'ÅLAND ISLANDS', 'name' => 'Euro', 'code' => 'EUR', 'description' => 'ISO numeric code: 978'],
        ];
        DB::table('ticket_currency')->upsert(
            array_map(
                fn(array $currency) => $currency + [
                    'created_at' => $now,
                    'updated_at' => $now,
                    'who' => 'VerificationSeeder',
                ],
                $currencies
            ),
            ['country_name', 'code'],
            ['name', 'description', 'updated_at', 'who']
        );
    }

    private function seedNames(string $table, array $names, mixed $now): void
    {
        $rows = array_map(
            fn(string $name) => [
                'name' => $name,
                'description' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'who' => 'VerificationSeeder',
            ],
            $names
        );

        DB::table($table)->upsert(
            $rows,
            ['name'],
            ['description', 'updated_at', 'who']
        );
    }

    private function stage(string $name, string $code, mixed $now): array
    {
        return [
            'name' => $name,
            'code' => $code,
            'description' => null,
            'created_at' => $now,
            'updated_at' => $now,
            'who' => 'VerificationSeeder',
        ];
    }
}
