/**
 * Error object used for Laravel API failures.
 *
 * Laravel validation errors are available through:
 *
 * error.errors.ticket_min
 * error.errors.country_ids
 * error.errors.funding_instrument_ids
 */
export class MatchingApiError extends Error {
  constructor(message, options = {}) {
    super(message);

    this.name = "MatchingApiError";
    this.status = options.status ?? 0;
    this.errors = options.errors ?? {};
    this.payload = options.payload ?? null;
  }
}

/**
 * Read the CSRF token generated by Laravel.
 *
 * Your main Blade layout must contain:
 *
 * <meta name="csrf-token" content="{{ csrf_token() }}">
 */
function getCsrfToken() {
  return (
    document
      .querySelector('meta[name="csrf-token"]')
      ?.getAttribute("content") ?? ""
  );
}

/**
 * Send a request to Laravel and parse its JSON response.
 */
async function requestJson(
  url,
  {
    method = "GET",
    body = undefined,
    signal = undefined,
  } = {},
) {
  const normalizedMethod = method.toUpperCase();

  const headers = {
    Accept: "application/json",
    "X-Requested-With": "XMLHttpRequest",
  };

  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
  }

  /*
   * Laravel web routes require a valid CSRF token for POST,
   * PUT, PATCH, and DELETE operations.
   */
  if (!["GET", "HEAD"].includes(normalizedMethod)) {
    const csrfToken = getCsrfToken();

    if (csrfToken) {
      headers["X-CSRF-TOKEN"] = csrfToken;
    }
  }

  const response = await fetch(url, {
    method: normalizedMethod,
    headers,
    credentials: "same-origin",
    signal,
    body:
      body === undefined
        ? undefined
        : JSON.stringify(body),
  });

  const contentType =
    response.headers.get("content-type") ?? "";

  let payload = null;

  if (response.status !== 204) {
    if (contentType.includes("application/json")) {
      payload = await response.json();
    } else {
      payload = await response.text();
    }
  }

  if (!response.ok) {
    const message =
      typeof payload === "object" && payload?.message
        ? payload.message
        : typeof payload === "string" && payload
          ? payload
          : `The request failed with status ${response.status}.`;

    throw new MatchingApiError(message, {
      status: response.status,
      errors:
        typeof payload === "object"
          ? payload?.errors ?? {}
          : {},
      payload,
    });
  }

  return payload;
}

/**
 * Load countries, sectors, and funding instruments.
 */
export function fetchMatchingOptions(signal) {
  return requestJson("/services/options", {
    signal,
  });
}

/**
 * Save the investor preference and execute the matching service.
 */
export function createMatchSearch(payload) {
  return requestJson("/services/matches", {
    method: "POST",
    body: payload,
  });
}

/**
 * Retrieve all previous searches for the authenticated investor.
 */
export function fetchSearchHistory(page = 1, signal) {
  return requestJson(
    `/services/matches/history?page=${page}`,
    {
      signal,
    },
  );
}

/**
 * Retrieve previously stored matching results.
 */
export function fetchSavedSearch(preferenceId) {
  return requestJson(
    `/services/matches/history/${encodeURIComponent(
      preferenceId,
    )}`,
  );
}

/**
 * Run the matching algorithm again using a saved preference.
 */
export function rerunSavedSearch(preferenceId) {
  return requestJson(
    `/services/matches/history/${encodeURIComponent(
      preferenceId,
    )}/rerun`,
    {
      method: "POST",
    },
  );
}